
SELECT id, nome, email, FROM clientes LIMIT 10


SELECT id, nome, email FROM clientes ORDER BY id DESC LIMIT 10


--IMAGINA QUE QUERES VER OS CLIENTES 6 A 10.

SELECT id, nome, email FROM clientes LIMIT 5 OFFSET 5

-- NESTE CASO VAI IGNORAR AS PRIMEIRAS 10 E VAI DEVOLVER AS 3 SEGUINTES.

SELECT id, nome, email, FROM clientes LIMIT 3 OFFSET 10;

-- OUTRA FORMA MAIS CURTA DE ESCREVER O MESMO CÓDIGO:

SELECT id, nome, email FROM clientes LIMIT 10, 3

-- AGORA VAMOS BUSCAR APENAS O FRUTO MAIS CARO
SELECT * FROM produtos ORDER BY preco_unidade DESC LIMIT 1;

-- AGORA VAMOS BUSCAR O FRUTO MAIS CARO

SELECT * FROM produtos ORDER BY preco_unidade ASC LIMIT 1;

-- E COMO IR BUSCAR O TERCEIRO MAIS CARO ?
SELECT * FROM produtos ORDER BY preco_unidade DESC LIMIT 2,1;
